artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/sandeeppvn/Sales-Deal-Discount-Optimization/blob/main/Data/DealData.xlsx
  local_data_file: artifacts/data_ingestion/DealData.xlsx
  